"""Interactive installation & provider configuration assistant.

Run ``python setup.py`` to be guided through selecting an LLM provider, entering
and validating the relevant API key, choosing a workspace directory and writing
a structured ``.env`` file consumed by :mod:`config`.

The script uses :mod:`rich` for a polished CLI when available and degrades
gracefully to plain ``input()`` prompts otherwise.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from config import DEFAULT_MODELS, LLMProvider

try:  # Optional pretty CLI.
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt
    from rich.table import Table

    _console: "Console | None" = Console()
except Exception:  # noqa: BLE001
    _console = None


# --------------------------------------------------------------------------- #
# Output helpers (rich-aware, but always functional)
# --------------------------------------------------------------------------- #
def _print(message: str) -> None:
    if _console:
        _console.print(message)
    else:
        print(re.sub(r"\[/?[^\]]+\]", "", message))


def _ask(prompt: str, default: str | None = None, password: bool = False) -> str:
    if _console:
        return Prompt.ask(prompt, default=default, password=password)
    suffix = f" [{default}]" if default else ""
    raw = input(f"{re.sub(r'[[/][^]]+]', '', prompt)}{suffix}: ").strip()
    return raw or (default or "")


# --------------------------------------------------------------------------- #
# Provider selection + key validation
# --------------------------------------------------------------------------- #
PROVIDERS = [
    (LLMProvider.OPENAI, "OpenAI (GPT-4o)"),
    (LLMProvider.ANTHROPIC, "Anthropic (Claude 3.5 Sonnet)"),
    (LLMProvider.GEMINI, "Google Gemini (Gemini 1.5 Pro)"),
    (LLMProvider.OLLAMA, "Ollama (local, no API key)"),
]

#: Rudimentary per-provider key format checks.
KEY_PATTERNS = {
    LLMProvider.OPENAI: re.compile(r"^sk-[A-Za-z0-9_\-]{20,}$"),
    LLMProvider.ANTHROPIC: re.compile(r"^sk-ant-[A-Za-z0-9_\-]{20,}$"),
    LLMProvider.GEMINI: re.compile(r"^[A-Za-z0-9_\-]{30,}$"),
}

ENV_KEY_NAMES = {
    LLMProvider.OPENAI: "OPENAI_API_KEY",
    LLMProvider.ANTHROPIC: "ANTHROPIC_API_KEY",
    LLMProvider.GEMINI: "GOOGLE_API_KEY",
}


def choose_provider() -> LLMProvider:
    if _console:
        table = Table(title="Select your LLM provider", show_lines=False)
        table.add_column("#", justify="right", style="cyan")
        table.add_column("Provider")
        table.add_column("Default model", style="green")
        for idx, (prov, label) in enumerate(PROVIDERS, start=1):
            table.add_row(str(idx), label, DEFAULT_MODELS[prov])
        _console.print(table)
    else:
        print("\nSelect your LLM provider:")
        for idx, (prov, label) in enumerate(PROVIDERS, start=1):
            print(f"  {idx}) {label}  [default model: {DEFAULT_MODELS[prov]}]")

    while True:
        choice = _ask("[bold]Enter a number (1-4)[/bold]", default="1")
        if choice.isdigit() and 1 <= int(choice) <= len(PROVIDERS):
            return PROVIDERS[int(choice) - 1][0]
        _print("[red]Invalid choice, please enter a number between 1 and 4.[/red]")


def prompt_api_key(provider: LLMProvider) -> str:
    if provider is LLMProvider.OLLAMA:
        return ""
    pattern = KEY_PATTERNS.get(provider)
    while True:
        key = _ask(f"[bold]Enter your {provider.value} API key[/bold]", password=True).strip()
        if not key:
            _print("[red]An API key is required for this provider.[/red]")
            continue
        if pattern and not pattern.match(key):
            _print(
                "[yellow]Warning: this key does not match the expected format "
                f"for {provider.value}.[/yellow]"
            )
            if _ask("Use it anyway? (y/n)", default="n").lower() != "y":
                continue
        return key


# --------------------------------------------------------------------------- #
# .env writing
# --------------------------------------------------------------------------- #
def write_env(provider: LLMProvider, api_key: str, workspace: str, model: str) -> Path:
    lines = [
        "# Generated by Aegis-X Enterprise setup.py",
        f"LLM_PROVIDER={provider.value}",
        f"MODEL_NAME={model}",
        f"WORKSPACE_PATH={workspace}",
        "COMMAND_TIMEOUT=45",
        "MAX_ITERATIONS=50",
        "MAX_HEALING_ATTEMPTS=3",
        "HOST=127.0.0.1",
        "PORT=8000",
        "LOG_LEVEL=INFO",
    ]
    if provider is LLMProvider.OLLAMA:
        lines.append("OLLAMA_BASE_URL=http://localhost:11434")
    elif api_key:
        lines.append(f"{ENV_KEY_NAMES[provider]}={api_key}")

    env_path = Path(__file__).resolve().parent / ".env"
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return env_path


def main() -> int:
    banner = "Aegis-X Enterprise — Interactive Setup"
    if _console:
        _console.print(Panel.fit(f"[bold cyan]{banner}[/bold cyan]", border_style="cyan"))
    else:
        print(f"\n=== {banner} ===\n")

    provider = choose_provider()
    api_key = prompt_api_key(provider)

    default_model = DEFAULT_MODELS[provider]
    model = _ask("[bold]Model name[/bold]", default=default_model) or default_model

    default_ws = str((Path(__file__).resolve().parent / "workspace"))
    workspace = _ask("[bold]Workspace directory[/bold]", default=default_ws) or default_ws
    Path(workspace).mkdir(parents=True, exist_ok=True)

    env_path = write_env(provider, api_key, workspace, model)

    _print(f"\n[green]✓ Configuration written to[/green] [bold]{env_path}[/bold]")
    _print(f"[green]✓ Provider:[/green] {provider.value}  [green]Model:[/green] {model}")
    _print(f"[green]✓ Workspace:[/green] {workspace}")
    _print("\nNext step: [bold]pip install -r requirements.txt[/bold] then [bold]python main.py[/bold]\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
